#!/bin/sh

echo -n "GET:    "
curl -X GET http://localhost:5000/readHello
echo

echo -n "POST:   "
curl -X POST http://localhost:5000/createHello
echo

echo -n "PUT:    "
curl -X PUT http://localhost:5000/updateHello
echo

echo -n "DELETE: "
curl -X DELETE http://localhost:5000/deleteHello
echo

